### ISSUE TITLE
0.1.16 significantly slows down compilation

### ISSUE THREAD

**Issue by danslapman** [tek/splain#9] opened 2017-01-20 11:57 UTC
After updating to 0.1.16 I experience a 4x compilation slowdown on my work project: clean compilation with 0.1.15 took 49 secods, now it takes 203 seconds (without any errors).

I use the following configuration:
```
  "-P:splain:implicits:false",
  "-P:splain:breakinfix:12",
```

Unfortunately, I cannot reproduce this issue with any of my open projects :(

**Comment by tek** [comment] 2017-01-20 15:08
I thought I noticed a slowdown during testing…the formatting routines are a little more complex now, I guess that huge implicit resolutions are impacted by that. I've been meaning to look into a way to delay the formatting until an error has occurred, because as it is, it happens whenever scalac generates an implicit message, which is multiple times for each (successful) resolution. Could be difficult though.

**Comment by tek** [comment] 2017-01-20 16:53
alright, delaying the formatting was easier than anticipated. could you test whether this brings compilation speed back to normal and close the issue if it works?

**Comment by danslapman** [comment] 2017-01-20 17:59
@tek for sure! In a few hours.

**Comment by nightscape** [comment] 2017-01-20 19:25
I just tried 0.1.17 and I think the slow-down is still present...

**Comment by danslapman** [comment] 2017-01-20 19:26
@tek 0.1.17 did not fix the situation, compilation time is equal to with 0.1.16

**Comment by tek** [comment] 2017-01-20 19:28
I see…so the slowdown isn't noticable with any other cases? I'll look into it some more, but eventually, you're going to have to come up with a test case.

**Comment by tek** [comment] 2017-01-20 19:36
just tried compiling a project of mine with heavy shapeless use, takes forever…maybe it's the same reason.

**Comment by danslapman** [comment] 2017-01-20 20:07
@tek I just got a 20% speed degradation on a small test project, I can share it if You still need a test case

**Comment by tek** [comment] 2017-01-20 20:14
yes, please

**Comment by danslapman** [comment] 2017-01-20 20:18
Hope it will help
https://github.com/danslapman/splain-test

**Comment by tek** [comment] 2017-01-21 02:28
alright, the problem is, that `foundReqMsg` is called lots of times during inference, independent of whether it eventually succeeds. This method is the only possible way of overriding that message, as all callers are objects or nested classes, so injecting a check if an actual error will be printed would require to duplicate half of the compiler code. I guess this just isn't possible from within a plugin.

**Comment by tek** [comment] 2017-01-21 13:05
Good news, everyone! I implemented simple caching and it brought compilation times back to normal dimensions in my test case. Please verify!

**Comment by danslapman** [comment] 2017-01-21 21:01
Just tested 0.1.20, in my case it even slighly (about 7%) than 0.1.15 👍

**Comment by tek** [comment] 2017-01-21 21:41
great! makes sense, the issue existed before, just wasn't that noticable until formatting became more complex.

**Closed by tek** 2017-01-21 21:41 UTC
